@baseUrl = http://localhost:3333
@verifyMailToken = {{verify.response.body.token}}
@authToken = {{authenticate.response.body.token}}

# @name register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "Bruno Fabre",
  "email": "bruno.hfabre@gmail.com"
}

###

# @name verify
POST {{baseUrl}}/verify-mail
Content-Type: application/json

{
  "email": "bruno.hfabre@gmail.com",
  "verificationCode": "412CFE"
}

###

# @name password
POST {{baseUrl}}/password
Content-Type: application/json
Authorization: Bearer {{verifyMailToken}}

{
  "password": "abcd1234"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "bruno.hfabre@gmail.com",
  "password": "abcd1234"
}
